#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Op {
    Adc,
    And,
    Asl,
    Bcc,
    Bcs,
    Beq,
    Bit,
    Bmi,
    Bne,
    Bpl,
    Bra,
    Brk,
    Brl,
    Bvc,
    Bvs,
    Clc,
    Cld,
    Cli,
    Clv,
    Cmp,
    Cpx,
    Cpy,
    Cop,
    Dec,
    Dex,
    Dey,
    Eor,
    Inc,
    Inx,
    Iny,
    Jmp,
    Jml,
    Jsr,
    Jsl,
    Lda,
    Ldx,
    Ldy,
    Lsr,
    Mvn,
    Mvp,
    Nop,
    Ora,
    Pea,
    Pei,
    Per,
    Pha,
    Phb,
    Phd,
    Phk,
    Php,
    Phx,
    Phy,
    Pla,
    Plb,
    Pld,
    Plp,
    Plx,
    Ply,
    Rep,
    Rol,
    Ror,
    Rti,
    Rts,
    Rtl,
    Sbc,
    Sec,
    Sed,
    Sei,
    Sep,
    Sta,
    Stx,
    Sty,
    Stp,
    Stz,
    Tax,
    Tay,
    Tcd,
    Tcs,
    Tdc,
    Tsc,
    Tsx,
    Txa,
    Txs,
    Txy,
    Tya,
    Tyx,
    Trb,
    Tsb,
    Wai,
    Wdm,
    Xba,
    Xce,
}

#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Am {
    Absolute,
    AbsoluteIndexedIndirect,
    AbsoluteIndirect,
    AbsoluteLong,
    AbsoluteLongX,
    AbsoluteX,
    AbsoluteY,
    Accumulator,
    Block,
    Direct,
    DirectIndexedIndirect,
    DirectIndirect,
    DirectIndirectIndexed,
    DirectIndirectIndexedLong,
    DirectIndirectLong,
    DirectX,
    DirectY,
    Immediate,
    Implied,
    Relative,
    RelativeLong,
    Stack,
    StackRelative,
    StackRelativeIndirectIndexed,
}

pub fn decode(opcode: u8) -> (Op, Am) {
    DECODE_ARR[opcode as usize]
}

static DECODE_ARR: [(Op, Am); 256] = [
    (Op::Brk, Am::Stack),
    (Op::Ora, Am::DirectIndexedIndirect),
    (Op::Cop, Am::Stack),
    (Op::Ora, Am::StackRelative),
    (Op::Tsb, Am::Direct),
    (Op::Ora, Am::Direct),
    (Op::Asl, Am::Direct),
    (Op::Ora, Am::DirectIndirectLong),
    (Op::Php, Am::Stack),
    (Op::Ora, Am::Immediate),
    (Op::Asl, Am::Accumulator),
    (Op::Phd, Am::Stack),
    (Op::Tsb, Am::Absolute),
    (Op::Ora, Am::Absolute),
    (Op::Asl, Am::Absolute),
    (Op::Ora, Am::AbsoluteLong),
    (Op::Bpl, Am::Relative),
    (Op::Ora, Am::DirectIndirectIndexed),
    (Op::Ora, Am::DirectIndirect),
    (Op::Ora, Am::StackRelativeIndirectIndexed),
    (Op::Trb, Am::Direct),
    (Op::Ora, Am::DirectX),
    (Op::Asl, Am::DirectX),
    (Op::Ora, Am::DirectIndirectIndexedLong),
    (Op::Clc, Am::Immediate),
    (Op::Ora, Am::AbsoluteY),
    (Op::Inc, Am::Accumulator),
    (Op::Tcs, Am::Immediate),
    (Op::Trb, Am::Absolute),
    (Op::Ora, Am::AbsoluteX),
    (Op::Asl, Am::AbsoluteX),
    (Op::Ora, Am::AbsoluteLongX),
    (Op::Jsr, Am::Absolute),
    (Op::And, Am::DirectIndexedIndirect),
    (Op::Jsl, Am::AbsoluteLong),
    (Op::And, Am::StackRelative),
    (Op::Bit, Am::Direct),
    (Op::And, Am::Direct),
    (Op::Rol, Am::Direct),
    (Op::And, Am::DirectIndirectLong),
    (Op::Plp, Am::Stack),
    (Op::And, Am::Immediate),
    (Op::Rol, Am::Accumulator),
    (Op::Pld, Am::Stack),
    (Op::Bit, Am::Absolute),
    (Op::And, Am::Absolute),
    (Op::Rol, Am::Absolute),
    (Op::And, Am::AbsoluteLong),
    (Op::Bmi, Am::Relative),
    (Op::And, Am::DirectIndirectIndexed),
    (Op::And, Am::DirectIndirect),
    (Op::And, Am::StackRelativeIndirectIndexed),
    (Op::Bit, Am::DirectX),
    (Op::And, Am::DirectX),
    (Op::Rol, Am::DirectX),
    (Op::And, Am::DirectIndirectIndexedLong),
    (Op::Sec, Am::Immediate),
    (Op::And, Am::AbsoluteY),
    (Op::Dec, Am::Accumulator),
    (Op::Tsc, Am::Immediate),
    (Op::Bit, Am::AbsoluteX),
    (Op::And, Am::AbsoluteX),
    (Op::Rol, Am::AbsoluteX),
    (Op::And, Am::AbsoluteLongX),
    (Op::Rti, Am::Stack),
    (Op::Eor, Am::DirectIndexedIndirect),
    (Op::Wdm, Am::Immediate),
    (Op::Eor, Am::StackRelative),
    (Op::Mvp, Am::Block),
    (Op::Eor, Am::Direct),
    (Op::Lsr, Am::Direct),
    (Op::Eor, Am::DirectIndirectLong),
    (Op::Pha, Am::Stack),
    (Op::Eor, Am::Immediate),
    (Op::Lsr, Am::Accumulator),
    (Op::Phk, Am::Stack),
    (Op::Jmp, Am::Absolute),
    (Op::Eor, Am::Absolute),
    (Op::Lsr, Am::Absolute),
    (Op::Eor, Am::AbsoluteLong),
    (Op::Bvc, Am::Relative),
    (Op::Eor, Am::DirectIndirectIndexed),
    (Op::Eor, Am::DirectIndirect),
    (Op::Eor, Am::StackRelativeIndirectIndexed),
    (Op::Mvn, Am::Block),
    (Op::Eor, Am::DirectX),
    (Op::Lsr, Am::DirectX),
    (Op::Eor, Am::DirectIndirectIndexedLong),
    (Op::Cli, Am::Immediate),
    (Op::Eor, Am::AbsoluteY),
    (Op::Phy, Am::Stack),
    (Op::Tcd, Am::Immediate),
    (Op::Jmp, Am::AbsoluteLong),
    (Op::Eor, Am::AbsoluteX),
    (Op::Lsr, Am::AbsoluteX),
    (Op::Eor, Am::AbsoluteLongX),
    (Op::Rts, Am::Stack),
    (Op::Adc, Am::DirectIndexedIndirect),
    (Op::Per, Am::Stack),
    (Op::Adc, Am::StackRelative),
    (Op::Stz, Am::Direct),
    (Op::Adc, Am::Direct),
    (Op::Ror, Am::Direct),
    (Op::Adc, Am::DirectIndirectLong),
    (Op::Pla, Am::Stack),
    (Op::Adc, Am::Immediate),
    (Op::Ror, Am::Accumulator),
    (Op::Rtl, Am::Stack),
    (Op::Jmp, Am::AbsoluteIndirect),
    (Op::Adc, Am::Absolute),
    (Op::Ror, Am::Absolute),
    (Op::Adc, Am::AbsoluteLong),
    (Op::Bvs, Am::Relative),
    (Op::Adc, Am::DirectIndirectIndexed),
    (Op::Adc, Am::DirectIndirect),
    (Op::Adc, Am::StackRelativeIndirectIndexed),
    (Op::Stz, Am::DirectX),
    (Op::Adc, Am::DirectX),
    (Op::Ror, Am::DirectX),
    (Op::Adc, Am::DirectIndirectIndexedLong),
    (Op::Sei, Am::Immediate),
    (Op::Adc, Am::AbsoluteY),
    (Op::Ply, Am::Stack),
    (Op::Tdc, Am::Immediate),
    (Op::Jmp, Am::AbsoluteIndexedIndirect),
    (Op::Adc, Am::AbsoluteX),
    (Op::Ror, Am::AbsoluteX),
    (Op::Adc, Am::AbsoluteLongX),
    (Op::Bra, Am::Relative),
    (Op::Sta, Am::DirectIndexedIndirect),
    (Op::Brl, Am::RelativeLong),
    (Op::Sta, Am::StackRelative),
    (Op::Sty, Am::Direct),
    (Op::Sta, Am::Direct),
    (Op::Stx, Am::Direct),
    (Op::Sta, Am::DirectIndirectLong),
    (Op::Dey, Am::Immediate),
    (Op::Bit, Am::Immediate),
    (Op::Txa, Am::Immediate),
    (Op::Phb, Am::Stack),
    (Op::Sty, Am::Absolute),
    (Op::Sta, Am::Absolute),
    (Op::Stx, Am::Absolute),
    (Op::Sta, Am::AbsoluteLong),
    (Op::Bcc, Am::Relative),
    (Op::Sta, Am::DirectIndirectIndexed),
    (Op::Sta, Am::DirectIndirect),
    (Op::Sta, Am::StackRelativeIndirectIndexed),
    (Op::Sty, Am::DirectX),
    (Op::Sta, Am::DirectX),
    (Op::Stx, Am::DirectY),
    (Op::Sta, Am::DirectIndirectIndexedLong),
    (Op::Tya, Am::Immediate),
    (Op::Sta, Am::AbsoluteY),
    (Op::Txs, Am::Immediate),
    (Op::Txy, Am::Immediate),
    (Op::Stz, Am::Absolute),
    (Op::Sta, Am::AbsoluteX),
    (Op::Stz, Am::AbsoluteX),
    (Op::Sta, Am::AbsoluteLongX),
    (Op::Ldy, Am::Immediate),
    (Op::Lda, Am::DirectIndexedIndirect),
    (Op::Ldx, Am::Immediate),
    (Op::Lda, Am::StackRelative),
    (Op::Ldy, Am::Direct),
    (Op::Lda, Am::Direct),
    (Op::Ldx, Am::Direct),
    (Op::Lda, Am::DirectIndirectLong),
    (Op::Tay, Am::Immediate),
    (Op::Lda, Am::Immediate),
    (Op::Tax, Am::Immediate),
    (Op::Plb, Am::Stack),
    (Op::Ldy, Am::Absolute),
    (Op::Lda, Am::Absolute),
    (Op::Ldx, Am::Absolute),
    (Op::Lda, Am::AbsoluteLong),
    (Op::Bcs, Am::Relative),
    (Op::Lda, Am::DirectIndirectIndexed),
    (Op::Lda, Am::DirectIndirect),
    (Op::Lda, Am::StackRelativeIndirectIndexed),
    (Op::Ldy, Am::DirectX),
    (Op::Lda, Am::DirectX),
    (Op::Ldx, Am::DirectY),
    (Op::Lda, Am::DirectIndirectIndexedLong),
    (Op::Clv, Am::Immediate),
    (Op::Lda, Am::AbsoluteY),
    (Op::Tsx, Am::Immediate),
    (Op::Tyx, Am::Immediate),
    (Op::Ldy, Am::AbsoluteX),
    (Op::Lda, Am::AbsoluteX),
    (Op::Ldx, Am::AbsoluteY),
    (Op::Lda, Am::AbsoluteLongX),
    (Op::Cpy, Am::Immediate),
    (Op::Cmp, Am::DirectIndexedIndirect),
    (Op::Rep, Am::Immediate),
    (Op::Cmp, Am::StackRelative),
    (Op::Cpy, Am::Direct),
    (Op::Cmp, Am::Direct),
    (Op::Dec, Am::Direct),
    (Op::Cmp, Am::DirectIndirectLong),
    (Op::Iny, Am::Immediate),
    (Op::Cmp, Am::Immediate),
    (Op::Dex, Am::Immediate),
    (Op::Wai, Am::Immediate),
    (Op::Cpy, Am::Absolute),
    (Op::Cmp, Am::Absolute),
    (Op::Dec, Am::Absolute),
    (Op::Cmp, Am::AbsoluteLong),
    (Op::Bne, Am::Relative),
    (Op::Cmp, Am::DirectIndirectIndexed),
    (Op::Cmp, Am::DirectIndirect),
    (Op::Cmp, Am::StackRelativeIndirectIndexed),
    (Op::Pei, Am::Stack),
    (Op::Cmp, Am::DirectX),
    (Op::Dec, Am::DirectX),
    (Op::Cmp, Am::DirectIndirectIndexedLong),
    (Op::Cld, Am::Immediate),
    (Op::Cmp, Am::AbsoluteY),
    (Op::Phx, Am::Stack),
    (Op::Stp, Am::Immediate),
    (Op::Jml, Am::AbsoluteIndirect),
    (Op::Cmp, Am::AbsoluteX),
    (Op::Dec, Am::AbsoluteX),
    (Op::Cmp, Am::AbsoluteLongX),
    (Op::Cpx, Am::Immediate),
    (Op::Sbc, Am::DirectIndexedIndirect),
    (Op::Sep, Am::Immediate),
    (Op::Sbc, Am::StackRelative),
    (Op::Cpx, Am::Direct),
    (Op::Sbc, Am::Direct),
    (Op::Inc, Am::Direct),
    (Op::Sbc, Am::DirectIndirectLong),
    (Op::Inx, Am::Immediate),
    (Op::Sbc, Am::Immediate),
    (Op::Nop, Am::Immediate),
    (Op::Xba, Am::Immediate),
    (Op::Cpx, Am::Absolute),
    (Op::Sbc, Am::Absolute),
    (Op::Inc, Am::Absolute),
    (Op::Sbc, Am::AbsoluteLong),
    (Op::Beq, Am::Relative),
    (Op::Sbc, Am::DirectIndirectIndexed),
    (Op::Sbc, Am::DirectIndirect),
    (Op::Sbc, Am::StackRelativeIndirectIndexed),
    (Op::Pea, Am::Stack),
    (Op::Sbc, Am::DirectX),
    (Op::Inc, Am::DirectX),
    (Op::Sbc, Am::DirectIndirectIndexedLong),
    (Op::Sed, Am::Immediate),
    (Op::Sbc, Am::AbsoluteY),
    (Op::Plx, Am::Stack),
    (Op::Xce, Am::Immediate),
    (Op::Jsr, Am::AbsoluteIndexedIndirect),
    (Op::Sbc, Am::AbsoluteX),
    (Op::Inc, Am::AbsoluteX),
    (Op::Sbc, Am::AbsoluteLongX),
];
